site_name: Databases
theme: readthedocs
pages:
  - Home: index.md
  - MySQL introduction: mysql-introduction.md
  - Retreiving data: retreiving-data.md
  - Sorting retreived data: sorting-retreived-data.md
  - Filtering data: filtering-data.md
  - Searching using Regular Expressions: searching-using-regular-expressions.md
  - Calculated fields: calculated-fields.md
  - Summarizing data: summarizing-data.md
  - Grouping data: grouping-data.md
  - Working with subqueries: subqueries.md
  - Joining tables: joins.md
  - Combining queries: combining-queries.md
  - Full-text searching: full-text-searching.md
  - Inserting data: inserting-data.md
  - Updating and deleting data: update-and-delete.md
  - Creating and manipulating tables: creating-and-manipulating-tables.md
  - Using views: views.md
  - Stored procedures: stored-procedures.md
  - Using cursors: cursors.md
  - Using triggers: triggers.md
  - Managing transaction processing: transactions.md
  - Globalization and localization: globalization-and-localization.md
  - Managing Security: security.md
  - Database maintenance: database-maintenance.md
